# Generated by Django 2.0 on 2017-12-03 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=1000)),
                ('to_location', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 12, 3, 18, 8, 54, 370966, tzinfo=utc))),
                ('train_number', models.CharField(max_length=8)),
                ('wagon', models.CharField(max_length=5)),
                ('place', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=254)),
                ('student_card_number', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2017, 12, 3, 18, 8, 54, 371148, tzinfo=utc))),
                ('need_to_change_ticket', models.BooleanField(default=False)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
            ],
        ),
    ]
