# Generated by Django 2.0 on 2017-12-03 00:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=1000)),
                ('to_location', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 12, 3, 0, 54, 40, 753242))),
                ('train_number', models.CharField(max_length=8)),
                ('wagon', models.CharField(max_length=5)),
                ('place', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('email', models.EmailField(max_length=254)),
                ('student_card_number', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2017, 12, 3, 0, 54, 40, 753453))),
                ('need_to_change_ticket', models.BooleanField(default=False)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
            ],
        ),
    ]
