# Generated by Django 2.0 on 2017-12-03 01:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20171203_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperson',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 1, 8, 52, 194357, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 1, 8, 52, 194046, tzinfo=utc)),
        ),
    ]
