# Generated by Django 2.0 on 2017-12-11 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20171211_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperson',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 12, 24, 10, 408370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 12, 24, 10, 408195, tzinfo=utc)),
        ),
    ]
