# Generated by Django 2.0 on 2017-12-25 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20171211_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperson',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
