# Generated by Django 2.0 on 2017-12-11 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20171211_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperson',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 9, 2, 50, 277147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bookingperson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 9, 2, 50, 276971, tzinfo=utc)),
        ),
    ]
