# Generated by Django 2.0 on 2017-12-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirm_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
