# Generated by Django 2.0 on 2017-12-09 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20171209_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='student_card_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
