# Generated by Django 2.0 on 2017-12-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_person_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.BookingPerson')),
                ('user', models.ManyToManyField(to='person.CustomUser')),
            ],
        ),
    ]
